"""
monthly-standard@1.0.0 Assessment Profile — Draft Baseline.

Enumerates ALL required capabilities for a full monthly AWS assessment:
- Global: billing, S3, CloudFront, Route 53, IAM
- Regional: EC2, EBS, EFS, Backup, Lambda, EKS, ECR, ALB, NLB, VPC, NAT,
            RDS, DynamoDB, ElastiCache, KMS, WAF, Secrets Manager,
            CloudWatch, CloudTrail, Config, SNS, MSK, Amazon MQ, Glue
- Derived: cost-optimization findings

Status: draft — cannot be activated until every required capability passes
readiness checks. Capabilities not yet migrated retain placeholder versions.

Implements: Req 5.1, 5.5, 10.1, 15.4, 16.3
"""

from __future__ import annotations

from decimal import Decimal

from agentic.models import (
    AssessmentProfile,
    CollectionWindow,
    RegionRule,
    RequiredProfileItem,
    SemVer,
)


# ---------------------------------------------------------------------------
# Global Capabilities (per account, global scope)
# ---------------------------------------------------------------------------

_GLOBAL_ITEMS: tuple[RequiredProfileItem, ...] = (
    RequiredProfileItem(
        capability_id="billing.summary",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "account_id",
            "service",
            "usage_type",
            "amount",
            "currency",
            "period",
            "provenance",
        ),
        target_scope="global",
        required_permissions=(
            "ce:GetCostAndUsage",
            "ce:GetCostForecast",
        ),
        not_applicable_rule=None,
    ),
    RequiredProfileItem(
        capability_id="s3.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "bucket_name",
            "account_id",
            "region",
            "creation_date",
            "versioning_status",
            "encryption_configuration",
            "public_access_block",
            "provenance",
        ),
        target_scope="global",
        required_permissions=(
            "s3:ListAllMyBuckets",
            "s3:GetBucketLocation",
            "s3:GetBucketVersioning",
            "s3:GetBucketEncryption",
            "s3:GetBucketPublicAccessBlock",
        ),
        not_applicable_rule=None,
    ),
    RequiredProfileItem(
        capability_id="cloudfront.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "distribution_id",
            "account_id",
            "domain_name",
            "status",
            "enabled",
            "origins",
            "provenance",
        ),
        target_scope="global",
        required_permissions=(
            "cloudfront:ListDistributions",
            "cloudfront:GetDistribution",
        ),
        not_applicable_rule=None,
    ),
    RequiredProfileItem(
        capability_id="route53.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "hosted_zone_id",
            "account_id",
            "name",
            "record_count",
            "is_private",
            "provenance",
        ),
        target_scope="global",
        required_permissions=(
            "route53:ListHostedZones",
            "route53:GetHostedZone",
            "route53:ListResourceRecordSets",
        ),
        not_applicable_rule=None,
    ),
    RequiredProfileItem(
        capability_id="iam.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "account_id",
            "user_name",
            "role_name",
            "policy_name",
            "create_date",
            "last_used",
            "provenance",
        ),
        target_scope="global",
        required_permissions=(
            "iam:ListUsers",
            "iam:ListRoles",
            "iam:ListPolicies",
            "iam:GetUser",
            "iam:GetRole",
        ),
        not_applicable_rule=None,
    ),
)


# ---------------------------------------------------------------------------
# Regional Capabilities (per account-region)
# ---------------------------------------------------------------------------

_REGIONAL_ITEMS: tuple[RequiredProfileItem, ...] = (
    RequiredProfileItem(
        capability_id="ec2.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "instance_id",
            "account_id",
            "region",
            "instance_type",
            "state",
            "launch_time",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=("ec2:DescribeInstances",),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="ebs.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "volume_id",
            "account_id",
            "region",
            "volume_type",
            "size_gb",
            "state",
            "encrypted",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=("ec2:DescribeVolumes",),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="efs.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "file_system_id",
            "account_id",
            "region",
            "performance_mode",
            "lifecycle_state",
            "size_bytes",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=("elasticfilesystem:DescribeFileSystems",),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="backup.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "backup_vault_name",
            "account_id",
            "region",
            "recovery_points_count",
            "encryption_key_arn",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=(
            "backup:ListBackupVaults",
            "backup:DescribeBackupVault",
        ),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="lambda.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "function_name",
            "account_id",
            "region",
            "runtime",
            "memory_size",
            "timeout",
            "last_modified",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=(
            "lambda:ListFunctions",
            "lambda:GetFunction",
        ),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="eks.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "cluster_name",
            "account_id",
            "region",
            "kubernetes_version",
            "status",
            "endpoint",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=(
            "eks:ListClusters",
            "eks:DescribeCluster",
        ),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="ecr.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "repository_name",
            "account_id",
            "region",
            "image_count",
            "encryption_type",
            "scan_on_push",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=(
            "ecr:DescribeRepositories",
            "ecr:ListImages",
        ),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="alb.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "load_balancer_arn",
            "account_id",
            "region",
            "dns_name",
            "scheme",
            "state",
            "type",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=("elasticloadbalancing:DescribeLoadBalancers",),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="nlb.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "load_balancer_arn",
            "account_id",
            "region",
            "dns_name",
            "scheme",
            "state",
            "type",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=("elasticloadbalancing:DescribeLoadBalancers",),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="vpc.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "vpc_id",
            "account_id",
            "region",
            "cidr_block",
            "state",
            "is_default",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=(
            "ec2:DescribeVpcs",
            "ec2:DescribeSubnets",
        ),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="nat.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "nat_gateway_id",
            "account_id",
            "region",
            "state",
            "subnet_id",
            "vpc_id",
            "connectivity_type",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=("ec2:DescribeNatGateways",),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="rds.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "db_instance_identifier",
            "account_id",
            "region",
            "engine",
            "engine_version",
            "instance_class",
            "storage_type",
            "multi_az",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=(
            "rds:DescribeDBInstances",
            "rds:DescribeDBClusters",
        ),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="dynamodb.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "table_name",
            "account_id",
            "region",
            "table_status",
            "billing_mode",
            "item_count",
            "table_size_bytes",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=(
            "dynamodb:ListTables",
            "dynamodb:DescribeTable",
        ),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="elasticache.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "cluster_id",
            "account_id",
            "region",
            "engine",
            "engine_version",
            "node_type",
            "num_cache_nodes",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=(
            "elasticache:DescribeCacheClusters",
            "elasticache:DescribeReplicationGroups",
        ),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="kms.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "key_id",
            "account_id",
            "region",
            "key_state",
            "key_usage",
            "key_manager",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=(
            "kms:ListKeys",
            "kms:DescribeKey",
        ),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="waf.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "web_acl_id",
            "account_id",
            "region",
            "name",
            "capacity",
            "rules_count",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=(
            "wafv2:ListWebACLs",
            "wafv2:GetWebACL",
        ),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="secretsmanager.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "secret_name",
            "account_id",
            "region",
            "rotation_enabled",
            "last_rotated_date",
            "last_accessed_date",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=(
            "secretsmanager:ListSecrets",
            "secretsmanager:DescribeSecret",
        ),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="cloudwatch.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "alarm_name",
            "account_id",
            "region",
            "state_value",
            "metric_name",
            "namespace",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=(
            "cloudwatch:DescribeAlarms",
            "cloudwatch:ListMetrics",
        ),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="cloudtrail.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "trail_name",
            "account_id",
            "region",
            "is_multi_region",
            "is_logging",
            "s3_bucket_name",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=(
            "cloudtrail:DescribeTrails",
            "cloudtrail:GetTrailStatus",
        ),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="config.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "recorder_name",
            "account_id",
            "region",
            "recording",
            "all_supported",
            "delivery_channel",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=(
            "config:DescribeConfigurationRecorders",
            "config:DescribeConfigurationRecorderStatus",
        ),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="sns.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "topic_arn",
            "account_id",
            "region",
            "display_name",
            "subscriptions_confirmed",
            "kms_master_key_id",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=(
            "sns:ListTopics",
            "sns:GetTopicAttributes",
        ),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="msk.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "cluster_name",
            "account_id",
            "region",
            "cluster_arn",
            "state",
            "kafka_version",
            "number_of_broker_nodes",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=(
            "kafka:ListClusters",
            "kafka:DescribeCluster",
        ),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="amazonmq.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "broker_id",
            "account_id",
            "region",
            "broker_name",
            "engine_type",
            "engine_version",
            "deployment_mode",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=(
            "mq:ListBrokers",
            "mq:DescribeBroker",
        ),
        not_applicable_rule="service-not-available-in-region",
    ),
    RequiredProfileItem(
        capability_id="glue.inventory",
        capability_version="1.0.0",
        required_fields=(
            "resource_identity",
            "database_name",
            "account_id",
            "region",
            "catalog_id",
            "create_time",
            "location_uri",
            "provenance",
        ),
        target_scope="regional",
        required_permissions=(
            "glue:GetDatabases",
            "glue:GetDatabase",
        ),
        not_applicable_rule="service-not-available-in-region",
    ),
)


# ---------------------------------------------------------------------------
# Derived Capabilities (cost optimization)
# ---------------------------------------------------------------------------

_DERIVED_ITEMS: tuple[RequiredProfileItem, ...] = (
    RequiredProfileItem(
        capability_id="cost-optimization.findings",
        capability_version="1.0.0",
        required_fields=(
            "rule_id",
            "rule_version",
            "resource_identity",
            "account_id",
            "region",
            "finding_details",
            "severity",
            "action",
            "estimated_savings",
            "pricing_provenance",
        ),
        target_scope="derived",
        required_permissions=(
            "ce:GetCostAndUsage",
            "ce:GetReservationUtilization",
            "ce:GetSavingsPlansUtilization",
            "trustedadvisor:DescribeCheckItems",
        ),
        not_applicable_rule=None,
    ),
)


# ---------------------------------------------------------------------------
# Factory
# ---------------------------------------------------------------------------


def create_monthly_standard_v1() -> AssessmentProfile:
    """
    Create the monthly-standard@1.0.0 assessment profile in draft status.

    This profile enumerates all required capabilities for a comprehensive
    monthly AWS assessment. It remains in draft status until every required
    capability passes readiness checks.

    Region rule: discovery mode (auto-detect enabled regions).
    Collection window: monthly (calendar month UTC).
    Completeness threshold: 1.0 (completed-empty counts as complete;
        failed/permission-denied/unsupported do not).
    Not-applicable rules: unsupported regional services and
        profile-declared global scope.
    """
    all_items = _GLOBAL_ITEMS + _REGIONAL_ITEMS + _DERIVED_ITEMS

    return AssessmentProfile(
        schema_id="assessment-profile",
        schema_version="1.0.0",
        profile_id="monthly-standard",
        version=SemVer(1, 0, 0),
        status="draft",
        items=all_items,
        region_rule=RegionRule(mode="discovery"),
        collection_window=CollectionWindow(period_type="monthly"),
        completeness_threshold=Decimal("1.0"),
    )
